FROM rust:bullseye AS chef
RUN cargo install cargo-chef
WORKDIR /app

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json
# Cache until here
COPY . .
RUN cargo build --bin proxy --release

FROM gcr.io/distroless/cc
COPY --from=builder /app/target/release/proxy /usr/local/bin/
ENTRYPOINT [ "/usr/local/bin/proxy" ]
