name: Rust

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: Build, test

    strategy:
      matrix:
        component:
          - proxy
          - broker

    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
#      - name: Login to DockerHub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: . # we need the .git directory
          file: Dockerfile.${{ matrix.component }}
          push: false
          platforms: linux/amd64,linux/arm64
          tags: samply/beam-${{ matrix.component }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max


#    - uses: actions-rs/toolchain@v1
#      with:
#        profile: minimal
#        toolchain: stable
#    - uses: Swatinem/rust-cache@v1
#    - name: Cargo (build)
#      run: cargo build --release
#    - name: Cargo (run tests)
#      run: tests/scripts/cargo-test.sh
#    - name: Upload Artifact ${{ matrix.component }}
#      uses: actions/upload-artifact@v3
#      with:
#        name: ${{ matrix.component }}
#        path: target/release/${{ matrix.component }}
